begin;

create table if not exists public.ess_scaff_tag_qr_labels (
  id uuid primary key default gen_random_uuid(),
  label_number bigint generated by default as identity unique not null,
  public_token uuid unique not null default gen_random_uuid(),
  company_entity_id text not null default 'ess'
    check (company_entity_id in ('ess', 'maloo')),
  status text not null default 'unassigned'
    check (status in ('unassigned', 'assigned', 'retired')),
  assigned_builder_id text,
  assigned_project_id text,
  assigned_form_id text,
  assigned_at timestamptz,
  retired_at timestamptz,
  retired_reason text,
  created_by_user_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint ess_scaff_tag_qr_labels_assignment_complete check (
    (status = 'assigned'
      and assigned_builder_id is not null
      and assigned_project_id is not null
      and assigned_form_id is not null
      and assigned_at is not null)
    or
    (status <> 'assigned')
  )
);

create unique index if not exists uq_ess_scaff_tag_qr_labels_active_form
  on public.ess_scaff_tag_qr_labels (assigned_builder_id, assigned_project_id, assigned_form_id)
  where status = 'assigned';

create index if not exists ix_ess_scaff_tag_qr_labels_status_number
  on public.ess_scaff_tag_qr_labels (status, label_number);

create or replace function public.touch_ess_scaff_tag_qr_labels_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_touch_ess_scaff_tag_qr_labels_updated_at
on public.ess_scaff_tag_qr_labels;

create trigger trg_touch_ess_scaff_tag_qr_labels_updated_at
before update on public.ess_scaff_tag_qr_labels
for each row
execute function public.touch_ess_scaff_tag_qr_labels_updated_at();

alter table public.ess_scaff_tag_qr_labels enable row level security;

drop policy if exists "authenticated_read_scaff_tag_qr_labels"
on public.ess_scaff_tag_qr_labels;
create policy "authenticated_read_scaff_tag_qr_labels"
on public.ess_scaff_tag_qr_labels
for select
to authenticated
using (true);

create or replace function public.generate_scaff_tag_qr_labels(
  p_quantity integer,
  p_company_entity_id text default 'ess'
)
returns setof public.ess_scaff_tag_qr_labels
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_company text := lower(btrim(coalesce(p_company_entity_id, 'ess')));
begin
  if p_quantity is null or p_quantity < 1 or p_quantity > 500 then
    raise exception 'Generate between 1 and 500 QR labels at a time.';
  end if;
  if normalized_company not in ('ess', 'maloo') then
    raise exception 'Unknown company entity.';
  end if;

  return query
  insert into public.ess_scaff_tag_qr_labels (company_entity_id, created_by_user_id)
  select normalized_company, auth.uid()
  from generate_series(1, p_quantity)
  returning *;
end;
$$;

create or replace function public.assign_scaff_tag_qr_label(
  p_public_token uuid,
  p_builder_id text,
  p_project_id text,
  p_form_id text,
  p_retire_existing boolean default false
)
returns public.ess_scaff_tag_qr_labels
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_label public.ess_scaff_tag_qr_labels;
  current_label public.ess_scaff_tag_qr_labels;
begin
  if nullif(btrim(p_builder_id), '') is null
     or nullif(btrim(p_project_id), '') is null
     or nullif(btrim(p_form_id), '') is null then
    raise exception 'Builder, project and form are required.';
  end if;

  select * into selected_label
  from public.ess_scaff_tag_qr_labels
  where public_token = p_public_token
  for update;

  if not found then
    raise exception 'This QR label is not recognised.';
  end if;
  if selected_label.status = 'retired' then
    raise exception 'This QR label has been retired and cannot be reused.';
  end if;
  if selected_label.status = 'assigned'
     and (selected_label.assigned_builder_id, selected_label.assigned_project_id, selected_label.assigned_form_id)
       is distinct from (btrim(p_builder_id), btrim(p_project_id), btrim(p_form_id)) then
    raise exception 'This QR label is already assigned to another Scaff-Tag.';
  end if;
  if p_retire_existing and selected_label.status = 'assigned' then
    raise exception 'Scan a different unassigned QR label to replace the current sticker.';
  end if;

  select * into current_label
  from public.ess_scaff_tag_qr_labels
  where status = 'assigned'
    and assigned_builder_id = btrim(p_builder_id)
    and assigned_project_id = btrim(p_project_id)
    and assigned_form_id = btrim(p_form_id)
  for update;

  if found and current_label.id <> selected_label.id then
    if not p_retire_existing then
      raise exception 'This Scaff-Tag already has a QR label. Use reassignment instead.';
    end if;

    update public.ess_scaff_tag_qr_labels
    set status = 'retired',
        retired_at = timezone('utc', now()),
        retired_reason = 'Replaced or damaged label',
        updated_at = timezone('utc', now())
    where id = current_label.id;
  end if;

  update public.ess_scaff_tag_qr_labels
  set status = 'assigned',
      assigned_builder_id = btrim(p_builder_id),
      assigned_project_id = btrim(p_project_id),
      assigned_form_id = btrim(p_form_id),
      assigned_at = timezone('utc', now()),
      retired_at = null,
      retired_reason = null
  where id = selected_label.id
  returning * into selected_label;

  return selected_label;
end;
$$;

create or replace function public.retire_scaff_tag_qr_label_when_form_deleted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.form_type = 'scaff-tags' then
    update public.ess_scaff_tag_qr_labels
    set status = 'retired',
        retired_at = timezone('utc', now()),
        retired_reason = 'Assigned Scaff-Tag was deleted',
        updated_at = timezone('utc', now())
    where status = 'assigned'
      and assigned_builder_id = old.builder_id
      and assigned_project_id = old.project_id
      and assigned_form_id = old.id;
  end if;
  return old;
end;
$$;

drop trigger if exists trg_retire_scaff_tag_qr_label_on_form_delete
on public.ess_safety_forms;

create trigger trg_retire_scaff_tag_qr_label_on_form_delete
after delete on public.ess_safety_forms
for each row
execute function public.retire_scaff_tag_qr_label_when_form_deleted();

revoke all on function public.generate_scaff_tag_qr_labels(integer, text) from public, anon;
revoke all on function public.assign_scaff_tag_qr_label(uuid, text, text, text, boolean) from public, anon;
grant execute on function public.generate_scaff_tag_qr_labels(integer, text) to authenticated;
grant execute on function public.assign_scaff_tag_qr_label(uuid, text, text, text, boolean) to authenticated;

notify pgrst, 'reload schema';

commit;
